import store from "@/store";

export default [
    {
        path: "pay",
        name: "AdminPay",
        component: () => import("@/views/zhifu/zhifu"),
        meta: { authLogin: true },
    },

    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "yonghu",
        name: "AdminyonghuList",
        component: () => import("@/views/yonghu/list"),
        meta: { title: "用户列表", authLogin: true },
    },
    {
        path: "yonghuadd",
        name: "AdminyonghuAdd",
        component: () => import("@/views/yonghu/add"),
        meta: { title: "添加用户", authLogin: true },
    },
    {
        path: "yonghuupdt",
        name: "AdminyonghuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "yonghuupdtself",
        name: "AdminyonghuUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "yonghudetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminyonghuDetail",
        component: () => import("@/views/yonghu/detail"),
        meta: { title: "用户详情", authLogin: true },
    },
    {
        path: "youqinglianjie",
        name: "AdminyouqinglianjieList",
        component: () => import("@/views/youqinglianjie/list"),
        meta: { title: "友情链接列表", authLogin: true },
    },
    {
        path: "youqinglianjieadd",
        name: "AdminyouqinglianjieAdd",
        component: () => import("@/views/youqinglianjie/add"),
        meta: { title: "添加友情链接", authLogin: true },
    },
    {
        path: "youqinglianjieupdt",
        name: "AdminyouqinglianjieUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/youqinglianjie/updt"),
        meta: { title: "编辑友情链接", authLogin: true },
    },
    {
        path: "lunbotu",
        name: "AdminlunbotuList",
        component: () => import("@/views/lunbotu/list"),
        meta: { title: "轮播图列表", authLogin: true },
    },
    {
        path: "lunbotuadd",
        name: "AdminlunbotuAdd",
        component: () => import("@/views/lunbotu/add"),
        meta: { title: "添加轮播图", authLogin: true },
    },
    {
        path: "lunbotuupdt",
        name: "AdminlunbotuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lunbotu/updt"),
        meta: { title: "编辑轮播图", authLogin: true },
    },
    {
        path: "pinglun",
        name: "AdminpinglunList",
        component: () => import("@/views/pinglun/list"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglun_pinglunren",
        name: "AdminpinglunListpinglunren",
        component: () => import("@/views/pinglun/list-pinglunren"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglunadd",
        name: "AdminpinglunAdd",
        component: () => import("@/views/pinglun/add"),
        meta: { title: "添加评论", authLogin: true },
    },
    {
        path: "pinglunupdt",
        name: "AdminpinglunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglun/updt"),
        meta: { title: "编辑评论", authLogin: true },
    },
    {
        path: "liulanjilu",
        name: "AdminliulanjiluList",
        component: () => import("@/views/liulanjilu/list"),
        meta: { title: "浏览记录列表", authLogin: true },
    },
    {
        path: "liulanjilu_liulanyonghu",
        name: "AdminliulanjiluListliulanyonghu",
        component: () => import("@/views/liulanjilu/list-liulanyonghu"),
        meta: { title: "浏览记录列表", authLogin: true },
    },
    {
        path: "liulanjiluadd",
        name: "AdminliulanjiluAdd",
        component: () => import("@/views/liulanjilu/add"),
        meta: { title: "添加浏览记录", authLogin: true },
    },
    {
        path: "liulanjiluupdt",
        name: "AdminliulanjiluUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/liulanjilu/updt"),
        meta: { title: "编辑浏览记录", authLogin: true },
    },
    {
        path: "gudongfenlei",
        name: "AdmingudongfenleiList",
        component: () => import("@/views/gudongfenlei/list"),
        meta: { title: "古董分类列表", authLogin: true },
    },
    {
        path: "gudongfenleiadd",
        name: "AdmingudongfenleiAdd",
        component: () => import("@/views/gudongfenlei/add"),
        meta: { title: "添加古董分类", authLogin: true },
    },
    {
        path: "gudongfenleiupdt",
        name: "AdmingudongfenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/gudongfenlei/updt"),
        meta: { title: "编辑古董分类", authLogin: true },
    },
    {
        path: "gudongxinxi",
        name: "AdmingudongxinxiList",
        component: () => import("@/views/gudongxinxi/list"),
        meta: { title: "古董信息列表", authLogin: true },
    },
    {
        path: "gudongxinxiadd",
        name: "AdmingudongxinxiAdd",
        component: () => import("@/views/gudongxinxi/add"),
        meta: { title: "添加古董信息", authLogin: true },
    },
    {
        path: "gudongxinxiupdt",
        name: "AdmingudongxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/gudongxinxi/updt"),
        meta: { title: "编辑古董信息", authLogin: true },
    },
    {
        path: "gudongxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmingudongxinxiDetail",
        component: () => import("@/views/gudongxinxi/detail"),
        meta: { title: "古董信息详情", authLogin: true },
    },
    {
        path: "lvyouhuodong",
        name: "AdminlvyouhuodongList",
        component: () => import("@/views/lvyouhuodong/list"),
        meta: { title: "旅游活动列表", authLogin: true },
    },
    {
        path: "lvyouhuodongadd",
        name: "AdminlvyouhuodongAdd",
        component: () => import("@/views/lvyouhuodong/add"),
        meta: { title: "添加旅游活动", authLogin: true },
    },
    {
        path: "lvyouhuodongupdt",
        name: "AdminlvyouhuodongUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lvyouhuodong/updt"),
        meta: { title: "编辑旅游活动", authLogin: true },
    },
    {
        path: "lvyouhuodongdetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminlvyouhuodongDetail",
        component: () => import("@/views/lvyouhuodong/detail"),
        meta: { title: "旅游活动详情", authLogin: true },
    },
    {
        path: "huodongbaoming",
        name: "AdminhuodongbaomingList",
        component: () => import("@/views/huodongbaoming/list"),
        meta: { title: "活动报名列表", authLogin: true },
    },
    {
        path: "huodongbaoming_baomingyonghu",
        name: "AdminhuodongbaomingListbaomingyonghu",
        component: () => import("@/views/huodongbaoming/list-baomingyonghu"),
        meta: { title: "活动报名列表", authLogin: true },
    },
    {
        path: "huodongbaomingadd",
        name: "AdminhuodongbaomingAdd",
        component: () => import("@/views/huodongbaoming/add"),
        meta: { title: "添加活动报名", authLogin: true },
    },
    {
        path: "huodongbaomingupdt",
        name: "AdminhuodongbaomingUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/huodongbaoming/updt"),
        meta: { title: "编辑活动报名", authLogin: true },
    },
    {
        path: "huodongbaomingdetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminhuodongbaomingDetail",
        component: () => import("@/views/huodongbaoming/detail"),
        meta: { title: "活动报名详情", authLogin: true },
    },
    {
        path: "shangpinfenlei",
        name: "AdminshangpinfenleiList",
        component: () => import("@/views/shangpinfenlei/list"),
        meta: { title: "商品分类列表", authLogin: true },
    },
    {
        path: "shangpinfenleiadd",
        name: "AdminshangpinfenleiAdd",
        component: () => import("@/views/shangpinfenlei/add"),
        meta: { title: "添加商品分类", authLogin: true },
    },
    {
        path: "shangpinfenleiupdt",
        name: "AdminshangpinfenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shangpinfenlei/updt"),
        meta: { title: "编辑商品分类", authLogin: true },
    },
    {
        path: "shouhuodizhi",
        name: "AdminshouhuodizhiList",
        component: () => import("@/views/shouhuodizhi/list"),
        meta: { title: "收货地址列表", authLogin: true },
    },
    {
        path: "shouhuodizhi_tianjiaren",
        name: "AdminshouhuodizhiListtianjiaren",
        component: () => import("@/views/shouhuodizhi/list-tianjiaren"),
        meta: { title: "收货地址列表", authLogin: true },
    },
    {
        path: "shouhuodizhiadd",
        name: "AdminshouhuodizhiAdd",
        component: () => import("@/views/shouhuodizhi/add"),
        meta: { title: "添加收货地址", authLogin: true },
    },
    {
        path: "shouhuodizhiupdt",
        name: "AdminshouhuodizhiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shouhuodizhi/updt"),
        meta: { title: "编辑收货地址", authLogin: true },
    },
    {
        path: "shouhuodizhidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminshouhuodizhiDetail",
        component: () => import("@/views/shouhuodizhi/detail"),
        meta: { title: "收货地址详情", authLogin: true },
    },
    {
        path: "shangpinxinxi",
        name: "AdminshangpinxinxiList",
        component: () => import("@/views/shangpinxinxi/list"),
        meta: { title: "商品信息列表", authLogin: true },
    },
    {
        path: "shangpinxinxiadd",
        name: "AdminshangpinxinxiAdd",
        component: () => import("@/views/shangpinxinxi/add"),
        meta: { title: "添加商品信息", authLogin: true },
    },
    {
        path: "shangpinxinxiupdt",
        name: "AdminshangpinxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shangpinxinxi/updt"),
        meta: { title: "编辑商品信息", authLogin: true },
    },
    {
        path: "shangpinxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminshangpinxinxiDetail",
        component: () => import("@/views/shangpinxinxi/detail"),
        meta: { title: "商品信息详情", authLogin: true },
    },
    {
        path: "gouwuche",
        name: "AdmingouwucheList",
        component: () => import("@/views/gouwuche/list"),
        meta: { title: "购物车列表", authLogin: true },
    },
    {
        path: "gouwuche_goumaiyonghu",
        name: "AdmingouwucheListgoumaiyonghu",
        component: () => import("@/views/gouwuche/list-goumaiyonghu"),
        meta: { title: "购物车列表", authLogin: true },
    },
    {
        path: "gouwucheadd",
        name: "AdmingouwucheAdd",
        component: () => import("@/views/gouwuche/add"),
        meta: { title: "添加购物车", authLogin: true },
    },
    {
        path: "gouwucheupdt",
        name: "AdmingouwucheUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/gouwuche/updt"),
        meta: { title: "编辑购物车", authLogin: true },
    },
    {
        path: "gouwuchedetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmingouwucheDetail",
        component: () => import("@/views/gouwuche/detail"),
        meta: { title: "购物车详情", authLogin: true },
    },
    {
        path: "dingdanxinxi",
        name: "AdmindingdanxinxiList",
        component: () => import("@/views/dingdanxinxi/list"),
        meta: { title: "订单信息列表", authLogin: true },
    },
    {
        path: "dingdanxinxi_xiadanyonghu",
        name: "AdmindingdanxinxiListxiadanyonghu",
        component: () => import("@/views/dingdanxinxi/list-xiadanyonghu"),
        meta: { title: "订单信息列表", authLogin: true },
    },
    {
        path: "dingdanxinxiadd",
        name: "AdmindingdanxinxiAdd",
        component: () => import("@/views/dingdanxinxi/add"),
        meta: { title: "添加订单信息", authLogin: true },
    },
    {
        path: "dingdanxinxiupdt",
        name: "AdmindingdanxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/dingdanxinxi/updt"),
        meta: { title: "编辑订单信息", authLogin: true },
    },
    {
        path: "dingdanxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmindingdanxinxiDetail",
        component: () => import("@/views/dingdanxinxi/detail"),
        meta: { title: "订单信息详情", authLogin: true },
    },
    {
        path: "dingdanfahuo",
        name: "AdmindingdanfahuoList",
        component: () => import("@/views/dingdanfahuo/list"),
        meta: { title: "订单发货列表", authLogin: true },
    },
    {
        path: "dingdanfahuo_xiadanyonghu",
        name: "AdmindingdanfahuoListxiadanyonghu",
        component: () => import("@/views/dingdanfahuo/list-xiadanyonghu"),
        meta: { title: "订单发货列表", authLogin: true },
    },
    {
        path: "dingdanfahuoadd",
        name: "AdmindingdanfahuoAdd",
        component: () => import("@/views/dingdanfahuo/add"),
        meta: { title: "添加订单发货", authLogin: true },
    },
    {
        path: "dingdanfahuoupdt",
        name: "AdmindingdanfahuoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/dingdanfahuo/updt"),
        meta: { title: "编辑订单发货", authLogin: true },
    },
    {
        path: "dingdanfahuodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmindingdanfahuoDetail",
        component: () => import("@/views/dingdanfahuo/detail"),
        meta: { title: "订单发货详情", authLogin: true },
    },
    {
        path: "dingdanqianshou",
        name: "AdmindingdanqianshouList",
        component: () => import("@/views/dingdanqianshou/list"),
        meta: { title: "订单签收列表", authLogin: true },
    },
    {
        path: "dingdanqianshou_qianshouyonghu",
        name: "AdmindingdanqianshouListqianshouyonghu",
        component: () => import("@/views/dingdanqianshou/list-qianshouyonghu"),
        meta: { title: "订单签收列表", authLogin: true },
    },
    {
        path: "dingdanqianshouadd",
        name: "AdmindingdanqianshouAdd",
        component: () => import("@/views/dingdanqianshou/add"),
        meta: { title: "添加订单签收", authLogin: true },
    },
    {
        path: "dingdanqianshouupdt",
        name: "AdmindingdanqianshouUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/dingdanqianshou/updt"),
        meta: { title: "编辑订单签收", authLogin: true },
    },
    {
        path: "dingdanqianshoudetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmindingdanqianshouDetail",
        component: () => import("@/views/dingdanqianshou/detail"),
        meta: { title: "订单签收详情", authLogin: true },
    },
    {
        path: "shangpinzixun",
        name: "AdminshangpinzixunList",
        component: () => import("@/views/shangpinzixun/list"),
        meta: { title: "商品咨询列表", authLogin: true },
    },
    {
        path: "shangpinzixun_zixunyonghu",
        name: "AdminshangpinzixunListzixunyonghu",
        component: () => import("@/views/shangpinzixun/list-zixunyonghu"),
        meta: { title: "商品咨询列表", authLogin: true },
    },
    {
        path: "shangpinzixunadd",
        name: "AdminshangpinzixunAdd",
        component: () => import("@/views/shangpinzixun/add"),
        meta: { title: "添加商品咨询", authLogin: true },
    },
    {
        path: "shangpinzixunupdt",
        name: "AdminshangpinzixunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shangpinzixun/updt"),
        meta: { title: "编辑商品咨询", authLogin: true },
    },
    {
        path: "shangpinzixundetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminshangpinzixunDetail",
        component: () => import("@/views/shangpinzixun/detail"),
        meta: { title: "商品咨询详情", authLogin: true },
    },
    {
        path: "huodongzixun",
        name: "AdminhuodongzixunList",
        component: () => import("@/views/huodongzixun/list"),
        meta: { title: "活动咨询列表", authLogin: true },
    },
    {
        path: "huodongzixun_zixunyonghu",
        name: "AdminhuodongzixunListzixunyonghu",
        component: () => import("@/views/huodongzixun/list-zixunyonghu"),
        meta: { title: "活动咨询列表", authLogin: true },
    },
    {
        path: "huodongzixunadd",
        name: "AdminhuodongzixunAdd",
        component: () => import("@/views/huodongzixun/add"),
        meta: { title: "添加活动咨询", authLogin: true },
    },
    {
        path: "huodongzixunupdt",
        name: "AdminhuodongzixunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/huodongzixun/updt"),
        meta: { title: "编辑活动咨询", authLogin: true },
    },
    {
        path: "huodongzixundetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminhuodongzixunDetail",
        component: () => import("@/views/huodongzixun/detail"),
        meta: { title: "活动咨询详情", authLogin: true },
    },
];
